spring:
  application:
    name: springboot-rest-jpa
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      write_dates_as_timestamps: false
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:blog;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS blog\\;CREATE SCHEMA IF NOT EXISTS audit"
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    properties:
      org:
        hibernate:
          show_sql: false
          format_sql: true
          envers:
            default_schema: audit
  flyway:
    default-schema: blog

security:
  jwt:
    secret-key: mysecret

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.envers.boot: ERROR

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    restart:
      enabled: true

jplaceholder:
  url: https://jsonplaceholder.typicode.com

blog:
  moderation:
    post:
      fixed-rate: 15000 # Every 15 seconds
    comment:
      cron: 0/20 * * * * * # Every 20 seconds
  cache:
    ttl: 50000 # 50 seconds



