create table blog.comment (
    id bigint generated by default as identity,
    content varchar(255) not null,
    author varchar(255) not null,
    creation_date timestamp not null,
    post_id bigint not null,
    created_by varchar(255) not null,
    created_date timestamp not null,
    generated_type VARCHAR(255) not null,
    last_modified_by varchar(255) not null,
    last_modified_date timestamp not null,
    version bigint not null,
    primary key (id),
    foreign key (post_id) references post(id)
);

create unique index blog.comment_index on blog.comment (author, content, post_id);

create table audit.comment_aud (
    id int8 not null,
    rev int4 not null,
    revtype int2,
    content varchar(255),
    author varchar(255),
    creation_date timestamp,
    generated_type VARCHAR(255),
    post_id bigint,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    version bigint,
    primary key (id, rev)
);