name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'adopt'
      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Install
        run: mvn install -DskipTests
      - name: Run Maven Tests
        run: mvn test -Dspring.profiles.active=test
      - name: Run Maven Package
        run: mvn clean package -DskipTests
      - name: Upload coverage to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Build Docker Image
#        if: ${{ contains(github.ref, 'main') }}
        run: docker build -t springboot-rest-jpa:latest .
